import kebabCase from 'lodash.kebabcase'

export default ({ title, body1, custom_javascript }) => {
  const logoSets = body1.reduce(
    (acc, slice) => ({
      ...acc,
      [kebabCase(slice.primary.name)]: slice.items.reduce(
        (logos, logo) => ({
          ...logos,
          [kebabCase(logo.name)]: logo.svg
        }),
        {}
      )
    }),
    {}
  )

  return `// Generated by Brand System for ${title[0].text}

window.brandSystem = ${JSON.stringify({ logoSets })};

const kebabCase = string => string
  .match(/[A-Z]{2,}(?=[A-Z][a-z]+[0-9]*|\b)|[A-Z]?[a-z]+[0-9]*|[A-Z]|[0-9]+/g)
  .map(x => x.toLowerCase())
  .join('-')

// Handle inline SVG logos 

const logoElements = document.querySelectorAll('[data-dynamic-logo]')
const staticLogoElements = document.querySelectorAll('[data-static-logo]')
const dataLogoSet = document.querySelector('[data-logo-set]').getAttribute('data-logo-set')
const logoSet = brandSystem.logoSets[dataLogoSet]

logoElements.forEach(logo => {
  const key = logo.getAttribute('data-dynamic-logo')
  const logoSVG = logoSet[key]
  logo.innerHTML = logoSVG
})

staticLogoElements.forEach(logo => {
  const key = logo.getAttribute('data-static-logo')
  const [collection, item] = key.split('.')
  const logoSVG = brandSystem.logoSets[collection][item]
  logo.innerHTML = logoSVG
})
${custom_javascript ? '\n' + custom_javascript + '\n' : ''}`
}
