import generateColors from './colors'
import generateTypography, { generateFontImports } from './typography'
import generateReset from './reset'
import generateCustomStyles from './custom'

export default brand => `/* Generated by Brand System for ${
  brand.title[0].text
} */

${generateFontImports(brand)}
${generateReset(brand)}
${generateTypography(brand)}
${generateColors(brand)}
${generateCustomStyles(brand)}
`
